name: Flatpak Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install flatpak
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak dbus-x11

    - name: Install just
      uses: extractions/setup-just@v2.0.0

    - name: Install Flatpak SDK, runtime and builder
      run: just flatpak deps

    - name: Validate AppStream metainfo
      run: just flatpak validate

    - name: Build Flatpak
      run: just flatpak build
