name: Flatpak Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install flatpak
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak dbus-x11

    - name: Add Flathub repository
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install just
      uses: extractions/setup-just@v2.0.0

    - name: Install Flatpak SDK, runtime and builder
      run: just deps-flatpak

    - name: Build Flatpak
      run: just build-flatpak
